# -*- coding: utf-8 -*-
"""07.07.02 Exercícios Listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA-7w6uZza1l-gkiU_nn-K0VJ6n-aoFQ

# Exercícios

## 1. Faturamento do Melhor e do Pior Mês do Ano

Qual foi o valor de vendas do melhor mês do Ano?
E valor do pior mês do ano?
"""

meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
vendas_1sem = [25000, 29000, 22200, 17750, 15870, 19900]
vendas_2sem = [19850, 100, 17540, 15555, 49051, 9650]

vendas_1sem.extend(vendas_2sem)

faturamento_melhor_mes = max(vendas_1sem)
faturamento_pior_mes = min(vendas_1sem)

print(faturamento_pior_mes)
print(faturamento_melhor_mes)

"""## 2. Continuação

Agora relacione as duas listas para printar 'O melhor mês do ano foi {} com {} vendas' e o mesmo para o pior mês do ano.

Calcule também o faturamento total do Ano e quanto que o melhor mês representou do faturamento total.

Obs: Para o faturamento total, pode usar a função sum(lista) que soma todos os itens de uma lista
"""

index_melhor_mes = vendas_1sem.index(faturamento_melhor_mes)
index_pior_mes = vendas_1sem.index(faturamento_pior_mes)

print('O melhor mes foi {} com {} vendas' .format(meses[index_melhor_mes],vendas_1sem[index_melhor_mes]))
print('O pior mes foi {} com {} vendas' .format(meses[index_pior_mes],vendas_1sem[index_pior_mes]))


"""## 3. Crie uma lista com o top 3 valores de vendas do ano (sem fazer "no olho")

Dica: o método remove retira um item da lista.
"""


top3 = []

maior_valor = max(vendas_1sem)
top3.append(maior_valor)

vendas_1sem.remove(maior_valor)

seg_maior_valor = max(vendas_1sem)
top3.append(seg_maior_valor)

vendas_1sem.remove(seg_maior_valor)

ter_maior_valor = max(vendas_1sem)
top3.append(ter_maior_valor)

print(top3)

